service: step-functions-example

functions: ${file(./resources/functions.yml)}

stepFunctions:
  stateMachines:
    main: ${file(./resources/state-machine.yml)}

provider:
  name: aws
  region: 'eu-central-1'
  stage: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  environment:
    tableName: ${self:custom.prefix}__BankAccountRequestTable
    region: ${self:provider.region}
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - states:SendTaskSuccess
        - states:SendTaskFailure
        - states:SendTaskHeartbeat
      Resource: 'arn:aws:states:*:*:*'
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: !GetAtt Database.Arn

resources: ${file(./resources/resources.yml)}

custom:
  prefix: ${self:service.name}-${self:provider.stage}
  webpack:
    packager: yarn
    webpackConfig: webpack.config.ts
    includeModules:
      forceExclude:
        - aws-sdk

package:
  individually: true

plugins:
  - serverless-step-functions
  - serverless-webpack
