Resources:
  Database:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.tableName}

      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: SK
          AttributeType: S

      BillingMode: PAY_PER_REQUEST
